version: "3.8"

services:
  geoscript:
    image: ebe/geo:latest
    depends_on:
      - mariadb
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geomex
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env.local
    expose:
      - 5000
    environment:
      - FLASK_APP=/app/src/manage.py
      - FLASK_ENV=development
    restart: "on-failure"
    command: bash -c "flask db upgrade
      && gunicorn -c wsgi.py manage:app"
    networks:
      - geonet

  mariadb:
    image: library/mariadb:10.5.5
    command: --max-allowed-packet=64MB
    container_name: geomaria
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: geomex
    ports:
      - "3320:3306"
    volumes:
      - geodata:/var/lib/mysql
    networks:
      - geonet

  nginx:
    image: library/nginx:1.19.2
    container_name: geonginx
    ports:
      - "80:80"
    depends_on:
      - geoscript
    networks:
      - geonet
    volumes:
      - ./nginx/geo.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  geodata:

networks:
  geonet:
