version: "3.8"

services:
  geoscript:
    image: ebe/geo:latest
    depends_on:
      - mariadb
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geomex
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env.local
    ports:
      - "9090:5000"
    command: bash -c "flask db upgrade && flask run --host=0"
    environment:
      - FLASK_APP=/app/src/manage.py
      - FLASK_ENV=development
    restart: "on-failure"

  mariadb:
    image: library/mariadb:10.5.5
    container_name: geomaria
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: geomex
    ports:
      - "3320:3306"
