version: "3.8"

services:
  geomex-server:
    build: .
    container_name: geomex-service
    depends_on:
      - mariadb
    volumes:
      - ./:/home/python/app/
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=/home/python/app/src/manage.py
      - FLASK_ENV=development
    command: /bin/sh -c "flask db upgrade --directory=/home/python/app/src/migrations && flask run --host=0.0.0.0"

  mariadb:
    image: library/mariadb:10.4.13
    container_name: db-geomex
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: develop
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: geomex
    volumes:
      - geomex:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  geomex:
