version: "3.8"

services:
  geoscript:
    image: ebe/geo:latest
    depends_on:
      - mariadb
      # - nginx
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geomex
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env.local
    ports:
      - "9090:5000"
    environment:
      - FLASK_APP=/app/src/manage.py
      - FLASK_ENV=development
    restart: "on-failure"

  mariadb:
    image: library/mariadb:10.5.5
    container_name: geomaria
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: geomex
    ports:
      - "3320:3306"
    volumes:
      - geodata:/var/lib/mysql

  # nginx:
  #  image: library/nginx:1.18.0
  #  container_name: geonginx
  #  ports:
  #    - "9090:80"
  #  environment:
  #    - NGINX_PORT=80

volumes:
  geodata:
